name: testDocker

on:
 push:
  branches: [master]


jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Build the Docker
    run: docker build -t logger .

  - name: Put logs
    run: docker run -it -v "$(pwd)/logs/:/home/logs/" logger
  - name: Put cf
    run: echo "1\n2\n3"
